
window.WrapMatchOrder1=function(sel,count,className){$('.order1_payment_wrapper').find('>*').unwrap();$('div.order1_payitems_wrapper div.description_box').remove();count=parseFloat(count);var elemWidth=(100/count)-1;sel.width(elemWidth+'%');for(var i=0;i<sel.length;i+=count){sel.slice(i,i+count).wrapAll('<div class="'+className+'" />');}
$('div.order1_payment_wrapper').append('<div class="description_box"></div>');}
var limit_exceeded=0;var Order1={calendar:{},flag:1,subflag:1,timeStamp:'',validateBon:function(){},chooseDeliveryMethod:function(box){if(box.is('.checked'))
{}
else
{$(".order1_big_checkbox").toggleClass("checked");$(".order1_delivery_title").toggleClass("active_title");$(".order1_shippings").toggleClass("inactive_shippings");$(".order1_shippings").children('.order1_delitem').each(function(){Order1.toggleDelivery($(this));});$(".order1_shippings").next('.order1_comment_background').css("visibility","visible");$(".inactive_shippings").next('.order1_comment_background').css("visibility","hidden");var previd=$('.o1selected').attr("id");var deliveryprefix;var deliverymethod;if(previd.length==12)
{deliveryprefix=previd.substring(0,11);deliverymethod=previd.substring(11,12);}
else
{deliveryprefix=previd.substring(0,12);deliverymethod=previd.substring(12,13);}
var nextid;var firstid=$('.order1_delitem').not('.o1inactive').not('.o1disabled').not('.o1dis_inactive').eq(0).attr("id");if(deliverymethod=="1")
{nextid=deliveryprefix+"0";Order1.subflag=Order1.flag;Order1.setFlag(1);}
else
{nextid=deliveryprefix+"1";}
Order1.deselectDelivery($("#"+previd));if($('#payment_2.o1selectedpay').length&&$('#order1_dvp.inactive_shippings').length){$('#payment_2').click();}}},showFields:function(id,calendar,time,prepaid,totaltime,minutetime)
{console.log(id,calendar,time,prepaid,totaltime,minutetime);Order1.getDeliveryAndPayform(id,$('#order1_payform input[name=payform_id]:checked').eq(0).val());if(minutetime=='0#0#0')minutetime='0#0#0#0#0';var day_totaltime='';var time_array=minutetime.split('#');var onlyDays=true;if(time_array[0]&&time_array[0]>0){if(time_array[0]==1){day_totaltime=time_array[0]+order1_showFields_day;}else{day_totaltime=time_array[0]+order1_txt_dni;}}
if(order1_txt_godz2!=''){if(time_array[1]&&time_array[1]>0){if(order1_txt_godz2!=''){var order1_txt_godz_variety=app_shop.fn.variety(time_array[1],order1_txt_godz,order1_txt_godz2);day_totaltime+=time_array[1]+order1_txt_godz_variety;}else{day_totaltime+=time_array[1]+order1_txt_godz;}
onlyDays=false;}
if(time_array[2]&&time_array[2]>0){day_totaltime+=time_array[2]+order1_txt_min;onlyDays=false;}}
$('.basketedit_summary_shipment_time > span, .order1_dvp_time_pick > div').hide();if(onlyDays&&time_array[4]&&time_array[4]==0&&txt_order1_shipping_10!=''){if((id=="0-0")||(id=="0-1")){$('.order1_delivery_time_pick_txt_auto').show().html(txt_order1_shipping_11);$('.order1_delivery_time_pick_auto').show().find('.order1_delivery_time_pick span').html(txt_order1_shipping_11);$('div.shipping_time_order1').hide();}else{$('.order1_delivery_time_pick_txt_auto').show().html(txt_order1_shipping_10);$('.order1_delivery_time_pick_auto').show().find('.order1_delivery_time_pick span').html(txt_order1_shipping_10);$('div.shipping_time_order1').show();}
$('div.basketedit_summary_shipment_time > b').html(txt_order1_shipping[parseInt(time_array[3])]);$('.order1_delivery_time_pick_auto .order1_delivery_time_pick_value').html(txt_order1_shipping[parseInt(time_array[3])]);$('.order1_delivery_time_pick_de').html(txt_order1_shipping_10_de);}else{if((id=="0-0")||(id=="0-1")){if(time_array[0]==0&&time_array[1]==0&&time_array[2]==0){$('.order1_delivery_time_pick_txt_4').show();}else{$('.order1_delivery_time_pick_txt_3').show();}
$('div.shipping_time_order1').hide();}
else{$('.order1_delivery_time_pick_txt_1').show();$('div.shipping_time_order1').show();}
$('.order1_delivery_time_pick').find('span').html(day_totaltime);$('div.basketedit_summary_shipment_time > b').html(day_totaltime);}
$('.order1_time_pick_button').hide();$('.order1_delivery_time_pick_hour').html('').hide();if(id[id.length-1]==1)
{$("#order1_calendar_info").show()
$("#order1_dvp_calendar_info").hide()}
else{$("#order1_calendar_info").hide()
$("#order1_dvp_calendar_info").show()}
if($('.unknown_delivery_time').length)
{$("#order1_calendar_info").hide()
$("#order1_dvp_calendar_info").hide()}
if((calendar!='n')&&(calendar!='')&&!((id=="0-0")||(id=="0-1")))
{$('.order1_time_pick_button').show();$('#calendar_select_active').val(1);if((id=="16-0")||(id=="16-1"))
{if($('#order1_calendar_deliveryown').size()){$("#order1_calendar_deliveryown").show()
$('#calendar_dateown_select').click();$("#order1_calendar_standard").hide()}else{$("#order1_calendar_standard").show()
Order1.printDates(time);}}
else
{if($('#order1_calendar_deliveryown').size()){$("#order1_calendar_deliveryown").hide()}
$("#order1_calendar_standard").show()
Order1.printDates(time);}
if(calendar=='t'){$('#calendar_select_hour_div').show();}else{$('#calendar_select_hour_div').hide();}}
else
{$('#calendar_select_active').val(0);$("#order1_calendar").hide();$('#calendar_select_hour_div,#order1_calendar_standard').hide();}
if(prepaid=='1'&&!saldo_payform_hide)
{$("#order1_payform").show()}
else
{$("#order1_payform").hide()}
if(payments_in_row=='')payments_in_row=7;if($('#order1_payform .o1selectedpay:visible').length)
$('#order1_payform .o1selectedpay').click();$('#order1_calendar_wrapper').hide();},toggleDelivery:function(obiekt){if(obiekt.is('.o1dis_inactive')||obiekt.is('.o1disabled'))
{obiekt.toggleClass("o1dis_inactive").toggleClass("o1disabled");}
else
{obiekt.toggleClass("o1inactive");}},selectDelivery:function(obiekt){obiekt.toggleClass("o1selected");obiekt.find("input[type=radio]").attr("checked",true);if(obiekt.find(".order1_delitem_price_point input").is(':checked')){$('input[name="shipping_for_points"]').val(1);}else{$('input[name="shipping_for_points"]').val(0);}
Order1.showComment(obiekt);$(".order1_text").val("");if(obiekt.attr('data-sameday')){setTimeout(function(){$('.sameday_date_wrapper').show();if(obiekt.attr('id').indexOf('delivery_24')>-1)
var currXPRESS='sameday';else if(obiekt.attr('id').indexOf('delivery_100069')>-1)
var currXPRESS='nextday';if(app_shop.vars.xpress_buffer[currXPRESS]){$('#sameday_date_sub').html('');$.each(app_shop.vars.xpress_buffer[currXPRESS],function(key,value){$('#sameday_date_sub').append('<div class="form-group"><input id="sameday_'+value.id+'" name="sameDayServiceId" class="order1_radio" value="'+value.id+'" type="radio"><label for="sameday_'+value.id+'" class="sameday_description">'+value.description+'</label></div>');});$('#sameday_date_sub').show();}else{$('#sameday_date_sub').html('');$('#sameday_date_sub').hide();}
if(app_shop.vars.xpress_active)
$('input[id="'+app_shop.vars.xpress_active+'"]').click();$('.basketedit_summary_shipment_time').hide();},100);}else{setTimeout(function(){$('.sameday_date_wrapper').hide();$('#sameday_date_sub').hide();$('.basketedit_summary_shipment_time').show();},100);}},deselectDelivery:function(obiekt){obiekt.removeClass("o1selected");obiekt.find("input[type=radio]").removeAttr("checked");},chooseDelivery:function(obiekt){console.log(obiekt);$('#order1_prepaid_comment_text,#order1_dvp_comment_text').hide();if(obiekt.parent().is('.inactive_shippings'))
{Order1.chooseDeliveryMethod(obiekt.parent().prev('.order1_delivery_label').children('.order1_big_checkbox checked'));Order1.deselectDelivery($('.o1selected'));Order1.selectDelivery(obiekt);}
else
{Order1.deselectDelivery($('.o1selected'));Order1.selectDelivery(obiekt);}
if(obiekt.parent().is('#order1_dvp')){$('.hideForCod').hide();}else{$('.hideForCod').show();}
setTimeout(function(){if(obiekt.parent().attr('id')=='order1_dvp'){$('input[name="chosenPayment"][value="tradeCredit"]').removeAttr('checked');$('input[name="chosenPayment"][value="prepaid"]').attr('checked','checked');}
if($('div.o1selectedpay:visible').length){if($('div.o1selectedpay:visible').size()){$('div.o1selectedpay').click();}else{$('div.order1_payment:visible:first').click();}}
if(obiekt.attr('data-sameday')=='true')
$('.order1_delivery_time_pick_auto, #order1_calendar_info, #order1_dvp_calendar_info').hide();},10)},showComment:function(obiekt){var comment=obiekt.find("input").attr("title");if(comment=="")
{$('.order1_delitem_comment').hide();}
else
{$('.order1_delitem_comment').hide();var txt_delivery=obiekt.find('input.order1_delitem_radio').attr("title");obiekt.find('.order1_delitem_comment').show().html(txt_delivery);}},getDeliveryAndPayform:function(d_id,p_id){clearTimeout(Order1.timeStamp);$('#order1_balance').addClass('loading_ajax');$('table#order1_balance').stop().fadeTo('fast',0.5);Order1.timeStamp=setTimeout(function(){var add_insurance_value=$('input[name=add_insurance]').is(':checked')?1:0;var _DeliveryData=$('input[name=shipping_for_points]').val()==1?{delivery:d_id,payform_id:p_id,add_insurance:add_insurance_value,shipping_for_points:1}:{delivery:d_id,payform_id:p_id,add_insurance:add_insurance_value}
$.getJSON('/ajax/basket-cost.php',_DeliveryData,function(data){$('table#order1_balance').fadeTo('fast',1);$('#order1_balance').removeClass('loading_ajax');$('#balance_products_worth').text(data.products_worth+data.currency_sign);$('#balance_prepaid_cost').text(data.total_additional_cost+data.currency_sign);$('#balance_total_to_pay').text(data.total_to_pay+data.currency_sign);var advance_value='';if($('#order1_dvp.inactive_shippings').length){if(advVal_mode=='total'){advance_value=Math.round((parseFloat(advVal_prepaid)+parseFloat(data.shipping_cost_after_rebate))*100)/100;}else{advance_value=advVal_prepaid;}}else{advance_value=advVal_dvp;}
$('strong.advance_value').html(format_price(advance_value,{mask:currency_format,currency:symbol.replace(/\s+/g,''),currency_space:currency_space,currency_before_price:currency_before_value}));$('strong.worth_value').html(format_price(data.products_worth,{mask:currency_format,currency:symbol.replace(/\s+/g,''),currency_space:currency_space,currency_before_price:currency_before_value}));$('strong.paymentcost_value').html(format_price(data.prepaid_cost,{mask:currency_format,currency:symbol.replace(/\s+/g,''),currency_space:currency_space,currency_before_price:currency_before_value}));if((data.prepaid_cost)&&(data.prepaid_cost>0)){$('strong.paymentcost_value').parent().show();}else{$('strong.paymentcost_value').parent().hide();}
$('strong.total_rebate').html(format_price(data.total_rebate_without_shipping,{mask:currency_format,currency:symbol.replace(/\s+/g,''),currency_space:currency_space,currency_before_price:currency_before_value}));if((data.total_rebate_without_shipping)&&(data.total_rebate_without_shipping>0)){$('strong.total_rebate').parent().show();}else{$('strong.total_rebate').parent().hide();}
if(data.shipping_cost_points){$('strong.shipping_value').html(data.shipping_cost_points+order1_pkt)}else{if((data.shipping_cost_after_rebate>0)){$('strong.shipping_value').html(format_price(data.shipping_cost_after_rebate,{mask:currency_format,currency:symbol.replace(/\s+/g,''),currency_space:currency_space,currency_before_price:currency_before_value}));$('strong.shipping_value').addClass('plus_sign');}else{if(data.shipping_cost>0){$('strong.shipping_value').html('<span><del>'+format_price(data.shipping_cost,{mask:currency_format,currency:symbol.replace(/\s+/g,''),currency_space:currency_space,currency_before_price:currency_before_value})+'</del></span> '+order1_gratis);$('strong.shipping_value').removeClass('plus_sign');}else{$('strong.shipping_value').html(order1_gratis);$('strong.shipping_value').removeClass('plus_sign');}}}
if(data.shipping_undefined==true){$('strong.shipping_value').parent().hide();}else{$('strong.shipping_value').parent().show();}
if((data.prepaid_discount)&&(data.prepaid_discount>0)){$('strong.prepaid_discount_value').parent().show();$('strong.prepaid_discount_value').html(format_price(data.prepaid_discount,{mask:currency_format,currency:symbol.replace(/\s+/g,''),currency_space:currency_space,currency_before_price:currency_before_value}));}else{$('strong.prepaid_discount_value').parent().hide();}
$('strong.insurance_value').html(format_price(data.insurance_cost,{mask:currency_format,currency:symbol.replace(/\s+/g,''),currency_space:currency_space,currency_before_price:currency_before_value}));if((data.insurance_cost)&&(data.insurance_cost>0)){$('strong.insurance_value').parent().show();}else{$('strong.insurance_value').parent().hide();}
$('strong.topay_value').html(format_price(data.total_to_pay,{mask:currency_format,currency:symbol.replace(/\s+/g,''),currency_space:currency_space,currency_before_price:currency_before_value})+((client_data_uses_vat!='false'&&app_shop.vars.vat_registered!='false')?gross_txt:''));if(parseFloat(limit_balance_value)<parseFloat(data.total_to_pay))
{limit_exceeded=1;$('div.limit_exceeded').attr('style','display:block;');$('strong.limit_touse').css('color','#FF0000');}
$('strong.saldo_value').html(data.payment_amount_from_client_balance_formatted);if(!saldo_limit_flag&&data.total_to_pay>0){$('#order1_prepaid .balance_title').html(saldo_txt['prepaid'][0]);$('#order1_dvp .balance_title').html(saldo_txt['dvp'][0]);saldo_payform_hide=false;if($('#order1_prepaid .o1selected').length>0){$("#order1_payform").show();}}else if(!saldo_limit_flag&&data.total_to_pay==0){$('#order1_prepaid .balance_title').html(saldo_txt['prepaid'][1]);$('#order1_dvp .balance_title').html(saldo_txt['dvp'][1]);saldo_payform_hide=true;$("#order1_payform").hide();}else if(saldo_limit_flag&&data.total_to_pay>0){$('#order1_prepaid .balance_title').html(saldo_txt['prepaid'][2]);$('#order1_dvp .balance_title').html(saldo_txt['dvp'][2]);saldo_payform_hide=false;if($('#order1_prepaid .o1selected').length>0){$("#order1_payform").show();}}else if(saldo_limit_flag&&data.total_to_pay==0){$('#order1_prepaid .balance_title').html(saldo_txt['prepaid'][3]);$('#order1_dvp .balance_title').html(saldo_txt['dvp'][3]);saldo_payform_hide=true;$("#order1_payform").hide();}
if(data.total_to_pay>0){$('div.order1_balance_info').show();}else{$('div.order1_balance_info').hide();}});},300);},choosePayment:function(obiekt){var paymentName=obiekt.data('payment_name')||' ';$('#discount_paiment_name').text(paymentName);Order1.getDeliveryAndPayform($('#order1_delivery input[name=shipping]:checked').eq(0).val(),$('#order1_payform input[name=payform_id]:checked').eq(0).val());$('input[name="chosenPayment"]').removeAttr('checked');if(obiekt.attr('id')=='payment_trade_credit'){$('.description_box').hide();$('input[name="chosenPayment"][value="tradeCredit"]').attr('checked','checked');}else{$('input[name="chosenPayment"][value="prepaid"]').attr('checked','checked');}
if(obiekt.parent().attr('id')=='order1_dvp'){$('input[name="chosenPayment"][value="tradeCredit"]').removeAttr('checked');$('input[name="chosenPayment"][value="prepaid"]').attr('checked','checked');}},setFlag:function(num){Order1.flag=num;},checkForm:function(){if(Order1.flag)
{return true;}},selectDate:function(obiekt){obiekt.toggleClass("o1selecteddate");obiekt.find("input[type=radio]").attr("checked",true);},inputDate:function(obiekt)
{$('.order1_delivery_time_pick_value').html(obiekt.find("input[type=radio]").attr('value'));$('div.basketedit_summary_shipment_time > b').html(obiekt.find("input[type=radio]").attr('value'));$('.basketedit_summary_shipment_time > span, .order1_dvp_time_pick > div').hide();$('.order1_delivery_time_pick_txt_2').show();},deselectDate:function(obiekt){obiekt.removeClass("o1selecteddate");obiekt.find("input[type=radio]").removeAttr("checked");},chooseDate:function(obiekt){Order1.deselectDate($('.o1selecteddate'));Order1.selectDate(obiekt);},setTime:function(dateText,inst){$("#order1_calbind").hide(order1_animspeed);var czas=$("#order1_calbind").datepicker('getDate');$("#calendar_date_select_7 span.order1_date_day").text(czas.getDate());$("#calendar_date_select_7 span.order1_date_month").text(iaical_monthNames2[parseInt(czas.getMonth())]);$("#calendar_date_select_7").click();},printDates:function(time)
{shopCalendar.printDays(Order1.calendar.D1,Order1.calendar.M1,Order1.calendar.Y1,time,'calendar_date_select_',7,Order1.calendar.holi)},working_days:function(days)
{Working_days=days;$("#order1_calbind").datepicker("refresh");},bind_desktop:function(){$('.payments_group_sub_content').on('click',function(){$(this).parent().toggleClass('group_open');})},bind_mobile:function(){$('.payments_group:not(#blik_payment):not(#simple_transfer_payment):not(#payment_later) .payments_group_sub_content').on('click',function(){$(this).parent().addClass('popup_payment_open');});$('.close_popup_payment').on('click',function(){$(this).parents('.payments_group').removeClass('popup_payment_open');});$('.change_payment_method').on('click',function(){var payment_group=$(this).parents('.payments_group');payment_group.find('.payment_icon').attr('src',payment_group.find('.payment_icon').attr('data-src'));$('.payments_group > input.selected_group').attr('checked',false);$('input[name="payform_id"]').attr('checked',false);payment_group.removeClass('popup_payment_open');payment_group.removeClass('group_open');});}}
function init_order1_calendar()
{$("#order1_calbind").datepicker({dateFormat:iaical_dateFormat,dayNamesMin:iaical_daysShort,defaultDate:Order1.calendar.Seldate,beforeShowDay:shopCalendar.setHolidays,minDate:Order1.calendar.Mindate,monthNames:iaical_monthNames,nextText:iaical_monthNext,prevText:iaical_monthPrev,onSelect:Order1.setTime,firstDay:iaical_firstDay,altField:'#calendar_date_select_7 input.order1_radio'}).hide();$("#calendar_date_select_8 div.order1_date_sub").live('click',function(){$("#order1_calbind").show(order1_animspeed);});};function Order1_attachClicks()
{$('#calendar_date_select_1').click(function(){Order1.inputDate($(this));});$('#calendar_date_select_2').click(function(){Order1.inputDate($(this));});$('#calendar_date_select_3').click(function(){Order1.inputDate($(this));});$('#calendar_date_select_4').click(function(){Order1.inputDate($(this));});$('#calendar_date_select_5').click(function(){Order1.inputDate($(this));});$('#calendar_date_select_6').click(function(){Order1.inputDate($(this));});$('#calendar_date_select_7').click(function(){Order1.inputDate($(this));});};function order1_init(){Order1.calendar=app_shop.vars.Order1.calendar;Order1.working_days(app_shop.vars.Order1.working_days_arr);Order1.showFields.apply(this,app_shop.vars.Order1.showFields_arr);if($('#order1_payform').length){$("input.order1_text").bind("keypress",function(e){if(e.keyCode==13)return false;});$('[name="calendar_select_hour"]').keyup(function(e){var temp=$('.order1_delivery_time_pick_value').html();$('.order1_delivery_time_pick_hour').html(calendar_in_time+$(this).val());if($('[name="calendar_select_hour"]').val().length>4){$('.order1_delivery_time_pick_hour').show();}else{$('.order1_delivery_time_pick_hour').hide();}});$('.runTopLayerOrder').click(function(){Order1_attachClicks();$('#order1_calendar_wrapper:not(.sameday_date_wrapper)').show();if(!$('div.o1selecteddate').size()){$('#calendar_date_select_1').click()}});$('.o1selected').click();if($('div.o1selectedpay:visible').length)
$('div.o1selectedpay').click();if(typeof(only_virtual)!='undefined'&&only_virtual=='yes')
{$('span.order1_delitem_time:not(.inactive_time)').parent().hide();$('#delivery_0-1').click();}
$('div.order1_shippings').click(function(){var objAdv=$('#advance_value, div.basketedit_product_summary.advance, #order1_payform_label_advance');var objOrd=$('#order1_payform_label_order');if(advance_type=='default'){if($('#advance_value').length){objAdv.show();objOrd.hide();}}else{if(advance_type=='prepaid'){if(!$(this).hasClass('inactive_shippings')&&$(this).attr('id')=='order1_prepaid'){objAdv.show();objOrd.hide();}else{objAdv.hide();objOrd.show();}}else{if(advance_type=='dvp'){if(!$(this).hasClass('inactive_shippings')&&$(this).attr('id')=='order1_dvp'){objAdv.show();objOrd.hide();}else{objAdv.hide();objOrd.show();}}else{objOrd.show();}}}});$('#insurance_products_order1 input[name=add_insurance]').click(function(){if($('#order1_balance').length>0){Order1.getDeliveryAndPayform($('#order1_delivery input[name=shipping]:checked').eq(0).val(),$('#order1_payform input[name=payform_id]:checked').eq(0).val());}})
if($('#payment_2.o1selectedpay').length&&$('#order1_dvp.inactive_shippings').length){$('#payment_2').click();}
if($('.o1selected')){$('.o1selected').find("input[type=radio]").attr("checked",true);}
if($('.o1selected')){$('.order1_payment').eq(0).addClass("order1_first");}
$('div.order1_delitem_pricebox input').click(function(){$(this).parents('div.order1_delitem_pricebox').find('input').removeAttr("checked");$(this).attr("checked",true);})
if($('.inactive_shippings')){$('.inactive_shippings').children('.order1_delitem').each(function(){Order1.toggleDelivery($(this));});$(".inactive_shippings").next('.order1_comment_background').css("visibility","hidden");}
$('#tsCheck input').click(function(){Order1.getDeliveryAndPayform($('#order1_delivery input[name=shipping]:checked').eq(0).val(),$('#order1_payform input[name=payform_id]:checked').eq(0).val());});if(limit_mode=='y')$('#order1_payform').addClass('payform_credit');if(!$('#order1_payform').is(':visible'))
Order1.choosePayment($('#payment_later'));app_shop.vars.xpress_buffer={};$('#show_sameday_dates').on('click',function(){var $this=$(this);var currCourier=$('.order1_delitem.o1selected').find('input.order1_delitem_radio').val();currCourier=currCourier.split('-');currCourier=currCourier[0];if(currCourier==24)
var currXPRESS='sameday';else
var currXPRESS='nextday';$.ajax({url:'/ajax/sameday.php?action=getHourOptions',type:'get',data:{courierId:currCourier},dataType:'json',beforeSend:function(){$('#content').addClass('load-content');},success:function(json){if(json.errno==0){$('#sameday_date_sub').html('');if(json.result.length>0){app_shop.vars.xpress_buffer[currXPRESS]={};$.each(json.result,function(key,value){var samedayDate='<div class="form-group">'
+'<input id="sameday_'+value.id+'" name="sameDayServiceId" class="order1_radio" value="'+value.id+'" type="radio">'
+'<label for="sameday_'+value.id+'" class="sameday_description">'+value.description+'</label>'
+'</div>';app_shop.vars.xpress_buffer[currXPRESS]['sameday_'+value.id]={id:value.id,description:value.description}
$('#sameday_date_sub').append(samedayDate);});}else
$('#sameday_date_sub').append('<p>'+xpress_couriers["not_available"]+'</p>');}else if(json.errno==2){Alertek.show_alert(xpress_couriers['errno_2']);}else if(json.errno==3){Alertek.show_alert(xpress_couriers['errno_3']);}
$('#content').removeClass('load-content');$('#sameday_date_sub').slideDown();},error:function(json){$('#content').removeClass('load-content');Alertek.show_alert(xpress_couriers["not_available"]);}});return false;});$('input[name="sameDayServiceId"]').live('change',function(){app_shop.vars.xpress_active=$(this).attr('id');});$('.order1_button').live('click',function(){if($('.order1_delitem[data-sameday="true"]').is('.o1selected')&&!$('input[name="sameDayServiceId"]:checked').val()){$('html, body').animate({scrollTop:$('.sameday_date_wrapper').offset().top-300},function(){Alertek.show_alert(xpress_couriers["choose_date"]);});return false;}});$('#order1_mobile_switcher a').on('click',function(){var $this=$(this);if(!$this.is('.active')){$this.siblings('a').removeClass('active');$this.parents('#order1_delivery').find('.order1_shippings').removeClass('active');$this.addClass('active');$this.parents('#order1_delivery').find($this.attr('href')).addClass('active');}
$("#order1_delivery .order1_shippings.active .o1inactive").first().trigger("click");return false;});}
if($('div.o1selectedpay').length)
$('div.o1selectedpay').click();}
function order1VisualChanges(obj){$('.payments_group .payment_icon').each(function(){$(this).attr('src',$(this).attr('data-src'));})
var current_payment_group=obj.parents('.payments_group');var current_payment_icon=obj.parents('.prepaid_payment').find('.prepaid_payment_icon').attr('src');current_payment_group.find('.payment_icon').attr('src',current_payment_icon);$('.payments_group > input.selected_group').attr('checked',false);$('.popup_payment_open').removeClass('popup_payment_open');current_payment_group.find('input.selected_group').attr('checked','checked');}
function setGiftcardError(obj){obj.parent('.has-feedback').removeClass('has-required').removeClass('has-success').addClass('has-error');}
function setGiftcardSuccess(obj){obj.parent('.has-feedback').removeClass('has-required').removeClass('has-error').addClass('has-success');}
function setGiftCardData(obj){$.ajax({url:'/ajax/gift-cards-and-vouchers.php',type:'POST',data:{action:'auth',number:obj.find('input[name="voucher_id"]').val(),pin:obj.find('input[name="pin_value"]').val()},success:function(json){if(json.errno==0){setGiftcardSuccess(obj.find('input[name="voucher_id"]'));setGiftcardSuccess(obj.find('input[name="pin_value"]'));$('.order1_form').append(obj.find('input').clone().hide());$('.order1_form').submit();}else{orderdetails_payments.ajaxLoadSite(0);if(obj.is('#giftcard_form')){if(json.errno=='auth_error_2'){setGiftcardError(obj.find('input[name="voucher_id"]'))
setGiftcardError(obj.find('input[name="pin_value"]'))
Alertek.show_alert(txt_order1_giftcard_02);}else if(json.errno=='auth_error_3'){setGiftcardError(obj.find('input[name="pin_value"]'))
Alertek.show_alert(txt_order1_giftcard_03);}else if(json.errno=='auth_error_4'){setGiftcardError(obj.find('input[name="voucher_id"]'))
Alertek.show_alert(txt_order1_giftcard_04);}else if(json.errno=='auth_error_5'){setGiftcardError(obj.find('input[name="voucher_id"]'))
setGiftcardError(obj.find('input[name="pin_value"]'))
Alertek.show_alert(txt_order1_giftcard_05);}else if(json.errno=='auth_error_6'){setGiftcardError(obj.find('input[name="pin_value"]'))
Alertek.show_alert(txt_order1_giftcard_06);}else if(json.errno=='auth_error_7'){setGiftcardError(obj.find('input[name="pin_value"]'))
Alertek.show_alert(txt_order1_giftcard_07);}}else{setGiftcardError(obj.find('input[name="voucher_id"]'))
Alertek.show_alert(txt_order1_voucher_01);}}}});}
app_shop.run(function(){$('.payments_group:not(#blik_payment):not(#simple_transfer_payment):not(#payment_later) .payments_group_sub_content').off();$('.close_popup_payment').off();$('.change_payment_method').off();$('.payments_group_sub_content').off();if(app_shop.vars.Order1.hasOwnProperty('calendar')){init_order1_calendar();}
order1_init();$('.payments_group .payment_icon').each(function(){$(this).attr('data-src',$(this).attr('src'));})
$('.order1_page input[name="payform_id"]:not(#payform_2):not(#payform_190)').on('change',function(){order1VisualChanges($(this));});order1VisualChanges($('.order1_page input[name="payform_id"]:checked'));$('.order1_page input[name="payform_id"]').on('change',function(){Order1.choosePayment($(this));});$('#payment_190').on('click',function(){order1VisualChanges($(this));$('body').dialog({content:$('#giftcard_data').html(),afterCloseFn:function(){$('.order1_page input[name="payform_id"]').removeAttr('checked');}});});$('#payment_2').on('click',function(){order1VisualChanges($(this));$('body').dialog({content:$('#voucher_data').html(),afterCloseFn:function(){$('.order1_page input[name="payform_id"]').removeAttr('checked');}});});$('#simple_transfer_payment > label, #blik_payment > label, #payment_later > label').on('click',function(){$(this).parent().find('input.hidden_input').click();});$('#dialog_wrapper .order1_giftcard_form .btn-large').on('click',function(){orderdetails_payments.ajaxLoadSite(1);orderdetails_payments.ajaxLoadSiteMessage('Weryfikacja danych');setGiftCardData($(this).parents('.order1_giftcard_form'));});if(app_shop.vars.view<3){Order1.bind_mobile();}else{Order1.bind_desktop();}
if(!$('input[name="payform_id"]:checked').length){$('input[name="payform_id"]').eq(0).click();}},'all','.order1_page');app_shop.run(function(){$('.payments_group:not(#blik_payment):not(#simple_transfer_payment):not(#payment_later) .payments_group_sub_content').off();$('.close_popup_payment').off();$('.change_payment_method').off();Order1.bind_mobile();},[1,2],'.order1_page');app_shop.run(function(){$('.payments_group:not(#blik_payment):not(#simple_transfer_payment):not(#payment_later) .payments_group_sub_content').off();$('.close_popup_payment').off();$('.change_payment_method').off();Order1.bind_desktop();},[3,4],'.order1_page');