
$.widget("custom.pickupcomplete",$.ui.autocomplete,{_resizeMenu:function(obj){this.menu.element.outerWidth(this.element.outerWidth());},_renderMenu:function(ul,items){items=items.sort(function(a,b){return a.value.toUpperCase()>b.value.toUpperCase()});ul.addClass('autocompletoverflow');$('label.pickup_point').hide();$.each(items,function(index,item){$('#pp_'+item.id).show();oneElement='<a onClick="$(\'.autocompletoverflow\').hide(); $(\'#pp_'+item.id+'\').click();" href="#pp_'+item.id+'">';oneElement+=item.value;oneElement+='</a>';$('<li class="ui-menu-item" role="menuitem" style="padding:5px;"></li>').data("item.autocomplete",item).append(oneElement).appendTo(ul);});}});var autocompleteData=[];var ajaxGetPickupNoMap=function(){$('.mapContainer_pickup, .pickupl_submit').show();var options={'courierId':pickup_sites.courierId,'isCod':pickup_sites.isCod};$.ajax({type:'GET',url:'/ajax/getPickups.php',data:options,dataType:'json',success:function(json){if(!json.pickupPoints.length){Alertek.show_alert(pickupl_nopoints);$('.loadingMap').hide();return false;}
setPickupPointsNoMap(json);},error:function(){orderdetails_payments.ajaxLoadSite(0);$('.no_google_api_key div.asideContainer_pickup').show();Alertek.show_alert(pickupl_error);}});}
var setPickupPointsNoMap=function(json){var pickup_clone_tmp=$('#pickup_copy').clone();var pickups='';for(i in json.pickupPoints){var pickup=json.pickupPoints[i];pickup_clone=pickup_clone_tmp.clone();pickup_clone.find('input[name=pickup_point], input[name=stock]').attr('id','pickup_point_'+pickup.id).val(pickup.id);pickup_clone.find('label').attr({'id':'pp_'+pickup.id,'data-latitude':pickup.coordinates.latitude,'data-longitude':pickup.coordinates.longitude,'data-id':pickup.id,'data-requires_client_number':pickup.requiresClientNumber,'for':'pickup_point_'+pickup.id});if(pickup.coordinates.longitude){pickup_clone.find('label .map_dir').attr('href','https://www.google.com/maps/dir/?api=1&destination='+pickup.coordinates.latitude+','+pickup.coordinates.longitude);}else{pickup_clone.find('label .map_dir').attr('href','https://maps.google.com?saddr=Current+Location&daddr='+pickup.address.street+'+'+pickup.address.postcode+'+'+pickup.address.city);}
pickup_clone.find('b.headerText').text(pickup.name);var pickup_street=pickup.address.buildingAndHouseNumber!=''?pickup.address.street+' '+pickup.address.buildingAndHouseNumber:pickup.address.street;pickup_clone.find('span.streetText').text(pickup_street);pickup_clone.find('span.zipcodePickup').html(pickup.address.postcode+' <span class="cityText">'+pickup.address.city+'</span>');pickup_clone.find('div.moreText').text(pickup.location);pickup_clone.find('a.moreLink').attr('href',pickup.link);if(!pickup.requiresClientNumber){pickup_clone.find('input[name=client_courier_number]').remove();}
pickups+=pickup_clone.html();autocompleteData.push({'label':pickup.address.city+', '+pickup.address.street+' '+pickup.address.buildingAndHouseNumber+' '+pickup.address.postcode+' '+pickup.id,'value':pickup.address.city+', '+pickup.address.street+' '+pickup.address.buildingAndHouseNumber+', '+pickup.id,'description':pickup.location,'id':pickup.id});}
$('#pickup_site .asideContainer_pickup').html(pickups);var accentMap={"ł":"l","ó":"o","ź":"z","ś":"s",",":"","  ":" "};var normalize=function(term){var ret="";var term=term.toLowerCase();for(var i=0;i<term.length;i++){ret+=accentMap[term.charAt(i)]||term.charAt(i);}
return ret.toLowerCase();};$("#autocomplete_location.autocomplete_nomap").pickupcomplete({minLength:4,delay:200,source:function(request,response){var regarr=$.trim(request.term).split(' ');var regarrLength=regarr.length;var RegExpArr=[];for(var key in regarr){if(regarr.hasOwnProperty(key)){var element=$.trim(regarr[key]);RegExpArr.push(new RegExp(element,'gi'));}}
response($.grep(autocompleteData,function(value){value=value.label;var match=0;for(index=0;index<RegExpArr.length;index++){var matcher=RegExpArr[index];if(matcher.test(value)||matcher.test(normalize(value))){match++;}}
if(match==regarrLength){return true;}}));},focus:function(event,ui){$("#searchpickup").val(ui.item.value);return false;},select:function(event,ui){$('#pp_'+ui.item.id).click();$('.asideContainer_pickup').scrollTop(0);$('.asideContainer_pickup').scrollTop($('#pickup_site [name="pickup_point"]:checked + label, #pickup_site [name="stock"]:checked + label').position().top);return false;}});var timeout=null;$("#autocomplete_location.autocomplete_nomap").live('input',function(){var that=$(this);clearTimeout(timeout);timeout=setTimeout(function(){if(that.val().length<3){$('label.pickup_point').show();}},500);});$('#autocomplete_location.autocomplete_nomap').trigger('keydown');setTimeout(function(){$('.no_google_api_key div.asideContainer_pickup').show();$('#autocomplete_location.autocomplete_nomap').trigger('blur');orderdetails_payments.ajaxLoadSite(0);},300)}
var pickup_sites={geokoder:0,mapa:0,zoom:0,markerIcon:0,language:0,markersArray:[],contentsArray:[],markerInfo:0,timeout:0,loadNavBoolPickup:false,pickupCount:0,pickupIteration:0,pickupFind:0,pickupFirstActive:true,calendar:{},markerAnimation:0,pickupsType:0,google_api_key:'',courierId:'',isCod:false,search_lat:'',search_lng:'',markerClusters:'',ClusterMaxZoom:13,minimumClusterSize:10,autocomplete:false,adress:{street_number:'',route:'',locality:'',administrative_area_level_1:'',country:'',postal_code:''},fillInAddress:function(place,manual){pickup_sites.adress={street_number:'',route:'',locality:'',administrative_area_level_1:'',country:'',postal_code:''};var componentForm={street_number:'short_name',route:'long_name',locality:'long_name',administrative_area_level_1:'short_name',country:'long_name',postal_code:'short_name'};pickup_sites.search_lat='';pickup_sites.search_lng='';if(place&&!place.geometry)return false;if(!place){$('div.asideContainer_pickup').prepend('<div class="menu_messages_message">'+pickupl_select_adress+'</div>');$('.loadingMap').hide();return false;}else{$('.mapContainer_pickup, .asideContainer_pickup, .pickupl_submit, #pickup_map').show();}
pickup_sites.search_lat=place.geometry.location.lat();pickup_sites.search_lng=place.geometry.location.lng();for(var i=0;i<place.address_components.length;i++){var addressType=place.address_components[i].types[0];if(componentForm[addressType]){var val=place.address_components[i][componentForm[addressType]];pickup_sites.adress[addressType]=val;}}
if(manual){var inputValue='';if(pickup_sites.adress.route){inputValue+=pickup_sites.adress.route;if(pickup_sites.adress.street_number){inputValue+=' '+pickup_sites.adress.street_number;}}
if(pickup_sites.adress.locality){if(pickup_sites.adress.route){inputValue+=', '}
inputValue+=pickup_sites.adress.locality;}
if(pickup_sites.adress.country){if(pickup_sites.adress.locality){inputValue+=', '}
inputValue+=pickup_sites.adress.country;}
$('#autocomplete_location').val(inputValue);}},getLocation:function(){if(pickup_sites.search_lat==''&&pickup_sites.search_lng==''){pickup_sites.geokoder.geocode({address:$('#autocomplete_location').val()},function(json,status){var point=(json&&json.length)?json[0]:null;pickup_sites.fillInAddress(point,true);pickup_sites.ajaxGetPickup(false);});}else{pickup_sites.ajaxGetPickup(false);}},ajaxGetPickup:function(radius){$('div.asideContainer_pickup .menu_messages_message').remove();var filterJSON=false;if(!pickup_sites.adress.locality){$('div.asideContainer_pickup').prepend('<div class="menu_messages_message">'+pickupl_select_adress+'</div>');$('.loadingMap').hide();return false;}else{$('.mapContainer_pickup, .asideContainer_pickup, .pickupl_submit, #pickup_map').show();}
$('label.pickup_point').hide();$('div.loadingMap').fadeIn('normal',function(){});$('span.loadingMarkers').hide();var options={'courierId':pickup_sites.courierId,'location[latitude]':pickup_sites.search_lat,'location[longitude]':pickup_sites.search_lng,'isCod':pickup_sites.isCod};if(radius){function getRadius(){var curr_zoom=pickup_sites.mapa.getZoom();if(curr_zoom>=15){return 1}else if(curr_zoom==14){return 2}else if(curr_zoom==13){return 4}else if(curr_zoom==12){return 7}else if(curr_zoom==11){return 10}else if(curr_zoom==10){return 15;}else{return 20;}}
var options={'courierId':pickup_sites.courierId,'location[latitude]':pickup_sites.search_lat,'location[longitude]':pickup_sites.search_lng,'radius':getRadius(),'isCod':pickup_sites.isCod};}
$.ajax({type:'GET',url:'/ajax/getPickups.php',data:options,dataType:'json',success:function(json){if(!jQuery.isEmptyObject(selected_pickup_point)){for(i in json.pickupPoints){if(json.pickupPoints[i].id==selected_pickup_point.id){delete json.pickupPoints[i];}}
json.pickupPoints.unshift(selected_pickup_point);}
if(!json.pickupPoints.length){if(radius){$('div.asideContainer_pickup').prepend('<div class="menu_messages_message">'+pickupl_nopoints_in_area+'</div>');}else{$('div.asideContainer_pickup').prepend('<div class="menu_messages_message">'+pickupl_nopoints+'</div>');}
$('.loadingMap').hide();return false;}
if(!pickup_sites.adress.route){for(i in json.pickupPoints){if($.trim(json.pickupPoints[i].address.city).toLowerCase()==$.trim(pickup_sites.adress.locality).toLowerCase()){options.radius=30;$.ajax({type:'GET',url:'/ajax/getPickups.php',data:options,dataType:'json',success:function(json){setPickupPoints(json,true);},error:function(){}});return false;}}}
setPickupPoints(json,false);},error:function(){$('div.asideContainer_pickup').prepend('<div class="menu_messages_message">'+pickupl_error+'</div>');}});},showSel:function(){pickup_sites.pickupCount=$('.asideContainer_pickup .pickup_point').length;pickup_sites.pickupIteration=0;$('div.loadingMap').fadeIn('normal',function(){});$('span.loadingMap').hide();$('span.loadingMarkers').css('display','block');$('span.loadingMarkersCount').text(pickup_sites.pickupCount);$('span.loadingMarkersComplete').text(pickup_sites.pickupIteration);pickup_sites.markersArray=[];var adresData=[]
$('.asideContainer_pickup .pickup_point').each(function(index){$this=$(this);adresData[index]={};adresData[index].idek=$this.data("id");adresData[index].headerText=$.trim($this.find(".headerText").text());adresData[index].streetText=$.trim($this.find(".streetText").text());adresData[index].cityText=$.trim($this.find(".cityText").text());adresData[index].moreText=$.trim($this.find(".moreLink").text());adresData[index].moreLink=$.trim($this.find(".moreLink").attr('href'));adresData[index].infoText=$.trim($this.find(".infoText").text());adresData[index].timeText=$.trim($this.find(".timeText").text());adresData[index].latitude=$.trim($this.data("latitude"));adresData[index].longitude=$.trim($this.data("longitude"));adresData[index].icon=$.trim($this.data('icon'));});var adresRow='';while(adresRow=adresData.pop()){if(adresRow.latitude&&adresRow.longitude){pickup_sites.findAdres(adresRow.headerText,adresRow.streetText,adresRow.cityText,adresRow.moreText,adresRow.moreLink,adresRow.infoText,adresRow.timeText,'none','another',false,adresRow.idek,adresRow.latitude,adresRow.longitude,adresRow.icon);}else{(function(adresRow){setTimeout(function(){pickup_sites.findAdres(adresRow.headerText,adresRow.streetText,adresRow.cityText,adresRow.moreText,adresRow.moreLink,adresRow.infoText,adresRow.timeText,'none','another',false,adresRow.idek,adresRow.latitude,adresRow.longitude,adresRow.icon);},pickup_sites.timeout);})(adresRow);}}},printDates:function(stockId){if(!$('#selectPickupDay').size())return false;var postData={stock_id:stockId}
$.ajax({type:'GET',url:'/ajax/basket-delivery.php',data:postData,dataType:'json',success:function(json){if(!json){$('#selectPickupDayWrapper').hide();return false};$('#selectPickupDay').html('');$.each(json,function(index,data){$('#selectPickupDay').append('<label class="pickupl_date"><input name="calendar_select_date" type="radio" class="pickupl_radio" value="'+data.date+'"></input><div class="pickupl_date_sub"><span class="pickupl_date_day">'+data.d+'</span><span class="pickupl_date_month">'+iaical_monthNames[data.m-1]+'</span></div></label>');});$('#selectPickupDayWrapper').show();$('.pickupl_hour_wrapper').show();$('#selectPickupDay [name="calendar_select_date"]').eq(1).attr('checked',true);},error:function(){Alertek.show_alert(pickupl_error);}});},setZoom:function(){var bounds=new google.maps.LatLngBounds();for(var i in pickup_sites.markersArray){bounds.extend(pickup_sites.markersArray[i].getPosition());}
pickup_sites.mapa.setCenter(bounds.getCenter());pickup_sites.mapa.fitBounds(bounds);pickup_sites.mapa.setZoom(pickup_sites.mapa.getZoom());if(pickup_sites.mapa.getZoom()>15){pickup_sites.mapa.setZoom(15);}},mapInit:function(){if($('.no_google_api_key').length){return false}
if($('#autocomplete_location').size()){pickup_sites.autocomplete=new google.maps.places.Autocomplete((document.getElementById('autocomplete_location')));$('label.pickup_point').hide();}
pickup_sites.zoom=pickupsZoom;pickup_sites.geokoder=new google.maps.Geocoder();var wspolrzedne=new google.maps.LatLng(parseInt(bCordPickups),parseInt(lCordPickups));if(markersAnimationPickups!='')
pickup_sites.markerAnimation=true;else
pickup_sites.markerAnimation=false;if(markerPickupsCustomIcon!='')
markerPickupsCustomIcon=true;else
markerPickupsCustomIcon=false;if(mapTypePickups=='ROADMAP')
var mapStyle=google.maps.MapTypeId.ROADMAP
else if(mapTypePickups=='SATELLITE')
var mapStyle=google.maps.MapTypeId.SATELLITE
else if(mapTypePickups=='HYBRID')
var mapStyle=google.maps.MapTypeId.HYBRID
else if(mapTypePickups=='TERRAIN')
var mapStyle=google.maps.MapTypeId.TERRAIN
else
var mapStyle=google.maps.MapTypeId.ROADMAP
if(navControlPickups!='')
navControlPickups=true;else
navControlPickups=false;if(mapTypeControlPickups!='')
mapTypeControlPickups=true;else
mapTypeControlPickups=false;if(scControlPickups!='')
scControlPickups=true;else
scControlPickups=false;if(controlTypePickups=='ZOOM_PAN')
var controlStyle=google.maps.NavigationControlStyle.ZOOM_PAN
else if(controlTypePickups=='SMALL')
var controlStyle=google.maps.NavigationControlStyle.SMALL
else if(controlTypePickups=='ANDROID')
var controlStyle=google.maps.NavigationControlStyle.ANDROID
else
var controlStyle=google.maps.NavigationControlStyle.ZOOM_PAN
if(mapTypeControlStylePickups=='DROPDOWN_MENU')
var TypeControlStyle=google.maps.MapTypeControlStyle.DROPDOWN_MENU
else if(mapTypeControlStylePickups=='HORIZONTAL_BAR')
var TypeControltyle=google.maps.MapTypeControlStyle.HORIZONTAL_BAR
else
var TypeControlStyle=google.maps.MapTypeControlStyle.DROPDOWN_MENU
if($('img.marker_face').attr('src')!=''&&markerPickupsCustomIcon){var markerIconSize=new google.maps.Size($('img.marker_face').width(),$('img.marker_face').height());var punkt_startowy=new google.maps.Point(0,0);var punkt_zaczepienia=new google.maps.Point(parseInt($('img.marker_face').width()/2),parseInt($('img.marker_face').height()/2));pickup_sites.markerIcon=new google.maps.MarkerImage($('img.marker_face').attr('src'),markerIconSize,punkt_startowy,punkt_zaczepienia);}
if(window['google_map_style_array']){var mapOptions={gestureHandling:'cooperative',zoom:pickup_sites.zoom,center:wspolrzedne,mapTypeId:mapStyle,navigationControl:navControlPickups,mapTypeControl:mapTypeControlPickups,scaleControl:scControlPickups,styles:google_map_style_array,navigationControlOptions:{style:controlStyle},mapTypeControlOptions:{style:TypeControlStyle}};}else{var mapOptions={gestureHandling:'cooperative',zoom:pickup_sites.zoom,center:wspolrzedne,mapTypeId:mapStyle,navigationControl:navControlPickups,mapTypeControl:mapTypeControlPickups,scaleControl:scControlPickups,navigationControlOptions:{style:controlStyle},mapTypeControlOptions:{style:TypeControlStyle}};}
if(pickup_sites.google_api_key===''){$('.pickupl_sel').removeAttr('disabled');$('div#ps_other').css('opacity','1.0');$('div#ps_other').css('cursor','pointer');}
pickup_sites.mapa=new google.maps.Map(document.getElementById("pickup_map"),mapOptions);pickup_sites.markerInfo=new google.maps.InfoWindow();google.maps.event.addListener(pickup_sites.mapa,'idle',function(){$('span.loadingMap').text($('span.loadingNav').text());});if(pickup_sites.autocomplete){pickup_sites.autocomplete.addListener('place_changed',function(){var place=pickup_sites.autocomplete.getPlace();pickup_sites.fillInAddress(place,false);pickup_sites.getLocation();});pickup_sites.getLocation();}else{pickup_sites.showSel();}},markerClickFunction:function(latlng,content){return function(e){e.cancelBubble=true;e.returnValue=false;if(e.stopPropagation){e.stopPropagation();e.preventDefault();}
pickup_sites.infoWindow.setContent(content);pickup_sites.infoWindow.setPosition(latlng);pickup_sites.infoWindow.open(pickup_sites.mapa);};},geokoderPrepare:function(point,status,headerText,streetText,cityText,moreText,moreLink,infoText,timeText,className,other,open,idek,latitude,longitude,icon){if(status==google.maps.GeocoderStatus.OK){pickup_sites.timeout=100;pickup_sites.pickupIteration++;pickup_sites.pickupFind++;var content='<div class="mapTooltip"><b class="mapTooltipName">'+headerText+'</b>';content+='<div class="mapTooltipAdress"><span>'+streetText+' </span> <span>'+cityText+'</span></div>';if(infoText){content+='<div class="mapTooltipComment">'+infoText+'</div>';}
content+='<div class="mapTooltipTime">'+timeText+'</div>';if(moreLink){content+='<div class="mapTooltipLink"><a class="btn-small" title="Zobacz szczegółowe informacje" href="'+moreLink+'" target="_blank">'+moreText+'</a></div>';}
content+='</div>';var opcjeMarkera={title:headerText,pickupPointID:idek};opcjeMarkera.position=point;opcjeMarkera.map=pickup_sites.mapa;if(pickup_sites.markerAnimation)
opcjeMarkera.animation=google.maps.Animation.DROP;if(icon&&icon!=''){opcjeMarkera.icon=icon;}else{if($('img.marker_face').attr('src')!=''&&markerPickupsCustomIcon){opcjeMarkera.icon=pickup_sites.markerIcon;}}
var marker=new google.maps.Marker(opcjeMarkera);pickup_sites.markersArray.push(marker);google.maps.event.addListener(marker,'click',(function(marker,i){return function(e){e.cancelBubble=true;e.returnValue=false;if(e.stopPropagation){e.stopPropagation();e.preventDefault();}
pickup_sites.markerInfo.setContent(content);pickup_sites.markerInfo.open(pickup_sites.mapa,marker);$('.asideContainer_pickup [value="'+marker.pickupPointID+'"]').attr('checked',true);$('.asideContainer_pickup').scrollTop(0);$('.asideContainer_pickup').scrollTop($('#pickup_site [name="pickup_point"]:checked + label').position().top);}})(marker,i));var pickupItem=$('.asideContainer_pickup [value="'+marker.pickupPointID+'"]').get(0);$('label[for="pickup_point_'+marker.pickupPointID+'"]').show().fadeTo('slow',1);google.maps.event.addDomListener(pickupItem,'click',(function(marker,i){return function(e){$('.asideContainer_pickup [value="'+marker.pickupPointID+'"]').attr('checked',true);pickup_sites.markerInfo.setContent(content);pickup_sites.mapa.setCenter(opcjeMarkera.position);if(pickup_sites.mapa.getZoom()<pickup_sites.ClusterMaxZoom){pickup_sites.mapa.setZoom(pickup_sites.ClusterMaxZoom+1);}
pickup_sites.markerInfo.open(pickup_sites.mapa,marker);}})(marker,i));if(pickup_sites.pickupIteration<pickup_sites.pickupCount){$('span.loadingMarkersComplete').text(pickup_sites.pickupIteration);}
if(pickup_sites.pickupIteration>=pickup_sites.pickupCount){setTimeout(function(){$('div.loadingMap').fadeOut('normal',function(){});var _src=$('.markerCluster[src*="m1.png"]').attr('src')
var _imagePath=_src.substring(0,_src.indexOf('1.png'));pickup_sites.setZoom();var create_map_selected_point=true;if(pickup_sites.mapa.zoom<pickup_sites.ClusterMaxZoom&&!jQuery.isEmptyObject(selected_pickup_point)){pickup_sites.minimumClusterSizeTMP=2}else{create_map_selected_point=false;pickup_sites.minimumClusterSizeTMP=pickup_sites.minimumClusterSize;}
if(!pickup_sites.markerClusters||create_map_selected_point){pickup_sites.markerClusters=new MarkerClusterer(pickup_sites.mapa,pickup_sites.markersArray,{imagePath:_imagePath,maxZoom:pickup_sites.ClusterMaxZoom,minimumClusterSize:pickup_sites.minimumClusterSizeTMP});}else{pickup_sites.markerClusters.clearMarkers()
pickup_sites.markerClusters.addMarkers(pickup_sites.markersArray);}
if(!jQuery.isEmptyObject(selected_pickup_point)){$('label.pickup_point:first-of-type').prev().attr('checked',true);pickup_sites.markerInfo.setContent(content);pickup_sites.markerInfo.open(pickup_sites.mapa,pickup_sites.markersArray[pickup_sites.markersArray.length-1]);selected_pickup_point={};}},300);}}else if(status==google.maps.GeocoderStatus.OVER_QUERY_LIMIT){pickup_sites.timeout+=50;setTimeout(function(){pickup_sites.findAdres(headerText,streetText,cityText,moreText,moreLink,infoText,timeText,className,other,open,idek,latitude,longitude,icon);},pickup_sites.timeout);}else{pickup_sites.pickupIteration++;if(pickup_sites.pickupIteration<=pickup_sites.pickupCount)
$('span.loadingMarkersComplete').text(pickup_sites.pickupIteration);if(pickup_sites.pickupIteration>=pickup_sites.pickupCount){setTimeout(function(){$('div.loadingMap').fadeOut('normal',function(){});var _src=$('.markerCluster[src*="m1.png"]').attr('src')
var _imagePath=_src.substring(0,_src.indexOf('1.png')-1);pickup_sites.setZoom();var create_map_selected_point=true;if(pickup_sites.mapa.zoom<pickup_sites.ClusterMaxZoom&&!jQuery.isEmptyObject(selected_pickup_point)){pickup_sites.minimumClusterSizeTMP=2;selected_pickup_point={};}else{create_map_selected_point=false;pickup_sites.minimumClusterSizeTMP=pickup_sites.minimumClusterSize;}
if(!pickup_sites.markerClusters||create_map_selected_point){pickup_sites.markerClusters=new MarkerClusterer(pickup_sites.mapa,pickup_sites.markersArray,{imagePath:_imagePath,maxZoom:pickup_sites.ClusterMaxZoom,minimumClusterSize:pickup_sites.minimumClusterSizeTMP});}else{pickup_sites.markerClusters.clearMarkers()
pickup_sites.markerClusters.addMarkers(pickup_sites.markersArray);}},300);}}},findAdres:function(headerText,streetText,cityText,moreText,moreLink,infoText,timeText,className,other,open,idek,latitude,longitude,icon){var adres=streetText+' , '+cityText;if(latitude&&longitude){var point=new google.maps.LatLng(latitude,longitude);pickup_sites.geokoderPrepare(point,'OK',headerText,streetText,cityText,moreText,moreLink,infoText,timeText,className,other,open,idek,latitude,longitude,icon);}else{pickup_sites.geokoder.geocode({address:adres},function(wyniki,status){var point=(wyniki&&wyniki.length)?wyniki[0].geometry.location:null;pickup_sites.geokoderPrepare(point,status,headerText,streetText,cityText,moreText,moreLink,infoText,timeText,className,other,open,idek,latitude,longitude,icon);});}},}
function init_pickupl_site(){if(pickup_sites.autocomplete){pickup_sites.autocomplete.setComponentRestrictions({'country':pickup_sites.country_code});}
if(typeof mapSiteType!='undefined')
if(mapSiteType=='pickup_site'){var loadingMapWidth=$('div.loadingMap').width()/2;var loadingMapHeight=$('div.loadingMap').height()/2;var loadingBoxWidth=$('div.loadingBox').width()/2;var loadingBoxHeight=$('div.loadingBox').height()/2;var loadingBoxLeft=loadingMapWidth-loadingBoxWidth;var loadingBoxTop=loadingMapHeight-loadingBoxHeight;pickup_sites.google_api_key=google_api_key;$('div.loadingBox').css('left',loadingBoxLeft);$('div.loadingBox').css('top',loadingBoxTop);$('div.loadingBox').fadeTo('normal',1.0,function(){});}
if($('.no_google_api_key').length){orderdetails_payments.ajaxLoadSite(1);ajaxGetPickupNoMap();}}
var setPickupPoints=function(json,filter){if(!$.isEmptyObject(pickup_sites.markersArray)){for(i in pickup_sites.markersArray){pickup_sites.markersArray[i].setMap(null);}}
$('#pickup_site .asideContainer_pickup').html('');if(filter){var pickupPointsFilter=[];for(i in json.pickupPoints){if($.trim(json.pickupPoints[i].address.city).toLowerCase()==$.trim(pickup_sites.adress.locality).toLowerCase()){pickupPointsFilter.push(json.pickupPoints[i]);}}
if(pickupPointsFilter.length){json.pickupPoints=pickupPointsFilter;}}
for(i in json.pickupPoints){var pickup=json.pickupPoints[i];var pickup_clone=$('#pickup_copy').clone();pickup_clone.find('input[name=pickup_point]').attr('id','pickup_point_'+pickup.id);pickup_clone.find('input[name=pickup_point]').val(pickup.id);pickup_clone.find('label').attr('data-latitude',pickup.coordinates.latitude);pickup_clone.find('label').attr('data-longitude',pickup.coordinates.longitude);pickup_clone.find('label').attr('data-id',pickup.id);pickup_clone.find('label').attr('data-requires_client_number',pickup.requiresClientNumber);pickup_clone.find('label').attr('for','pickup_point_'+pickup.id);pickup_clone.find('label').hide().css('opacity','0');if(pickup.markerIconUrl){pickup_clone.find('label').attr('data-icon',pickup.markerIconUrl);pickup_clone.find('label').find('svg').replaceWith('<img src="'+pickup.markerIconUrl+'" alt="'+pickup.id+'"/>');}
if(pickup.coordinates.longitude){pickup_clone.find('label .map_dir').attr('href','https://www.google.com/maps/dir/?api=1&destination='+pickup.coordinates.latitude+','+pickup.coordinates.longitude);}else{pickup_clone.find('label .map_dir').attr('href','https://maps.google.com?saddr=Current+Location&daddr='+pickup.address.street+'+'+pickup.address.postcode+'+'+pickup.address.city);}
pickup_clone.find('b.headerText').text(pickup.name);var pickup_street=pickup.address.buildingAndHouseNumber!=''&&pickup.address.buildingAndHouseNumber!=null?pickup.address.street+' '+pickup.address.buildingAndHouseNumber:pickup.address.street;pickup_clone.find('span.streetText').text(pickup_street);pickup_clone.find('span.zipcodePickup').html(pickup.address.postcode+' <span class="cityText">'+pickup.address.city+'</span>');pickup_clone.find('div.moreText').text(pickup.location);pickup_clone.find('a.moreLink').attr('href',pickup.link);if(pickup.requiresClientNumber){}else{pickup_clone.find('input[name=client_courier_number]').remove();}
$('#pickup_site .asideContainer_pickup').append(pickup_clone.find(' > *'));}
pickup_sites.showSel();}
function geolocate(){pickup_sites.search_lat='';pickup_sites.search_lng='';if(navigator.geolocation){navigator.geolocation.getCurrentPosition(function(position){var geolocation={lat:position.coords.latitude,lng:position.coords.longitude};var circle=new google.maps.Circle({center:geolocation,radius:position.coords.accuracy});pickup_sites.autocomplete.setBounds(circle.getBounds());});}}
$('#locationField .btn').live('click',function(){pickup_sites.getLocation();return false;});$('div.morePickup').live('click',function(){var activePoints=$('label.pickup_point.moreInfoShow')
$(this).parents('label.pickup_point').addClass('moreInfoShow');activePoints.removeClass('moreInfoShow');});$('#pickup_site [name="pickup_point"], #pickup_site [name="stock"]').live('click',function(){$('#pickup_site [name="client_courier_number"]').attr('disabled',true);$(this).find('+ label [name="client_courier_number"]').attr('disabled',false).focus();pickup_sites.printDates($(this).val());});app_shop.run(function(){pickup_sites.country_code=app_shop.vars.country_code;pickup_sites.language=app_shop.vars.language;pickup_sites.isCod=app_shop.vars.isCod;pickup_sites.courierId=app_shop.vars.courierId;init_pickupl_site();var mapLink='https://maps.googleapis.com/maps/api/js?key='+app_shop.vars.apiKey+'&libraries=places&callback=pickup_sites.mapInit';var pickup_src=document.createElement('script');pickup_src.setAttribute('src',mapLink);document.body.appendChild(pickup_src);},'all','#pickup_site');function MarkerClusterer(map,opt_markers,opt_options){this.extend(MarkerClusterer,google.maps.OverlayView);this.map_=map;this.markers_=[];this.clusters_=[];this.sizes=[53,56,66,78,90];this.styles_=[];this.ready_=false;var options=opt_options||{};this.gridSize_=options['gridSize']||60;this.minClusterSize_=options['minimumClusterSize']||2;this.maxZoom_=options['maxZoom']||null;this.styles_=options['styles']||[];this.imagePath_=options['imagePath']||this.MARKER_CLUSTER_IMAGE_PATH_;this.imageExtension_=options['imageExtension']||this.MARKER_CLUSTER_IMAGE_EXTENSION_;this.zoomOnClick_=true;if(options['zoomOnClick']!=undefined){this.zoomOnClick_=options['zoomOnClick'];}
this.averageCenter_=false;if(options['averageCenter']!=undefined){this.averageCenter_=options['averageCenter'];}
this.setupStyles_();this.setMap(map);this.prevZoom_=this.map_.getZoom();var that=this;google.maps.event.addListener(this.map_,'zoom_changed',function(){var zoom=that.map_.getZoom();var minZoom=that.map_.minZoom||0;var maxZoom=Math.min(that.map_.maxZoom||100,that.map_.mapTypes[that.map_.getMapTypeId()].maxZoom);zoom=Math.min(Math.max(zoom,minZoom),maxZoom);if(that.prevZoom_!=zoom){that.prevZoom_=zoom;that.resetViewport();}});google.maps.event.addListener(this.map_,'idle',function(){that.redraw();});if(opt_markers&&(opt_markers.length||Object.keys(opt_markers).length)){this.addMarkers(opt_markers,false);}}
MarkerClusterer.prototype.MARKER_CLUSTER_IMAGE_PATH_='../images/m';MarkerClusterer.prototype.MARKER_CLUSTER_IMAGE_EXTENSION_='png';MarkerClusterer.prototype.extend=function(obj1,obj2){return(function(object){for(var property in object.prototype){this.prototype[property]=object.prototype[property];}
return this;}).apply(obj1,[obj2]);};MarkerClusterer.prototype.onAdd=function(){this.setReady_(true);};MarkerClusterer.prototype.draw=function(){};MarkerClusterer.prototype.setupStyles_=function(){if(this.styles_.length){return;}
for(var i=0,size;size=this.sizes[i];i++){this.styles_.push({url:this.imagePath_+(i+1)+'.'+this.imageExtension_,height:size,width:size});}};MarkerClusterer.prototype.fitMapToMarkers=function(){var markers=this.getMarkers();var bounds=new google.maps.LatLngBounds();for(var i=0,marker;marker=markers[i];i++){bounds.extend(marker.getPosition());}
this.map_.fitBounds(bounds);};MarkerClusterer.prototype.setStyles=function(styles){this.styles_=styles;};MarkerClusterer.prototype.getStyles=function(){return this.styles_;};MarkerClusterer.prototype.isZoomOnClick=function(){return this.zoomOnClick_;};MarkerClusterer.prototype.isAverageCenter=function(){return this.averageCenter_;};MarkerClusterer.prototype.getMarkers=function(){return this.markers_;};MarkerClusterer.prototype.getTotalMarkers=function(){return this.markers_.length;};MarkerClusterer.prototype.setMaxZoom=function(maxZoom){this.maxZoom_=maxZoom;};MarkerClusterer.prototype.getMaxZoom=function(){return this.maxZoom_;};MarkerClusterer.prototype.calculator_=function(markers,numStyles){var index=0;var count=markers.length;var dv=count;while(dv!==0){dv=parseInt(dv/10,10);index++;}
index=Math.min(index,numStyles);return{text:count,index:index};};MarkerClusterer.prototype.setCalculator=function(calculator){this.calculator_=calculator;};MarkerClusterer.prototype.getCalculator=function(){return this.calculator_;};MarkerClusterer.prototype.addMarkers=function(markers,opt_nodraw){if(markers.length){for(var i=0,marker;marker=markers[i];i++){this.pushMarkerTo_(marker);}}else if(Object.keys(markers).length){for(var marker in markers){this.pushMarkerTo_(markers[marker]);}}
if(!opt_nodraw){this.redraw();}};MarkerClusterer.prototype.pushMarkerTo_=function(marker){marker.isAdded=false;if(marker['draggable']){var that=this;google.maps.event.addListener(marker,'dragend',function(){marker.isAdded=false;that.repaint();});}
this.markers_.push(marker);};MarkerClusterer.prototype.addMarker=function(marker,opt_nodraw){this.pushMarkerTo_(marker);if(!opt_nodraw){this.redraw();}};MarkerClusterer.prototype.removeMarker_=function(marker){var index=-1;if(this.markers_.indexOf){index=this.markers_.indexOf(marker);}else{for(var i=0,m;m=this.markers_[i];i++){if(m==marker){index=i;break;}}}
if(index==-1){return false;}
marker.setMap(null);this.markers_.splice(index,1);return true;};MarkerClusterer.prototype.removeMarker=function(marker,opt_nodraw){var removed=this.removeMarker_(marker);if(!opt_nodraw&&removed){this.resetViewport();this.redraw();return true;}else{return false;}};MarkerClusterer.prototype.removeMarkers=function(markers,opt_nodraw){var removed=false;for(var i=0,marker;marker=markers[i];i++){var r=this.removeMarker_(marker);removed=removed||r;}
if(!opt_nodraw&&removed){this.resetViewport();this.redraw();return true;}};MarkerClusterer.prototype.setReady_=function(ready){if(!this.ready_){this.ready_=ready;this.createClusters_();}};MarkerClusterer.prototype.getTotalClusters=function(){return this.clusters_.length;};MarkerClusterer.prototype.getMap=function(){return this.map_;};MarkerClusterer.prototype.setMap=function(map){this.map_=map;};MarkerClusterer.prototype.getGridSize=function(){return this.gridSize_;};MarkerClusterer.prototype.setGridSize=function(size){this.gridSize_=size;};MarkerClusterer.prototype.getMinClusterSize=function(){return this.minClusterSize_;};MarkerClusterer.prototype.setMinClusterSize=function(size){this.minClusterSize_=size;};MarkerClusterer.prototype.getExtendedBounds=function(bounds){var projection=this.getProjection();var tr=new google.maps.LatLng(bounds.getNorthEast().lat(),bounds.getNorthEast().lng());var bl=new google.maps.LatLng(bounds.getSouthWest().lat(),bounds.getSouthWest().lng());var trPix=projection.fromLatLngToDivPixel(tr);trPix.x+=this.gridSize_;trPix.y-=this.gridSize_;var blPix=projection.fromLatLngToDivPixel(bl);blPix.x-=this.gridSize_;blPix.y+=this.gridSize_;var ne=projection.fromDivPixelToLatLng(trPix);var sw=projection.fromDivPixelToLatLng(blPix);bounds.extend(ne);bounds.extend(sw);return bounds;};MarkerClusterer.prototype.isMarkerInBounds_=function(marker,bounds){return bounds.contains(marker.getPosition());};MarkerClusterer.prototype.clearMarkers=function(){this.resetViewport(true);this.markers_=[];};MarkerClusterer.prototype.resetViewport=function(opt_hide){for(var i=0,cluster;cluster=this.clusters_[i];i++){cluster.remove();}
for(var i=0,marker;marker=this.markers_[i];i++){marker.isAdded=false;if(opt_hide){marker.setMap(null);}}
this.clusters_=[];};MarkerClusterer.prototype.repaint=function(){var oldClusters=this.clusters_.slice();this.clusters_.length=0;this.resetViewport();this.redraw();window.setTimeout(function(){for(var i=0,cluster;cluster=oldClusters[i];i++){cluster.remove();}},0);};MarkerClusterer.prototype.redraw=function(){this.createClusters_();};MarkerClusterer.prototype.distanceBetweenPoints_=function(p1,p2){if(!p1||!p2){return 0;}
var R=6371;var dLat=(p2.lat()-p1.lat())*Math.PI/180;var dLon=(p2.lng()-p1.lng())*Math.PI/180;var a=Math.sin(dLat/2)*Math.sin(dLat/2)+
Math.cos(p1.lat()*Math.PI/180)*Math.cos(p2.lat()*Math.PI/180)*Math.sin(dLon/2)*Math.sin(dLon/2);var c=2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));var d=R*c;return d;};MarkerClusterer.prototype.addToClosestCluster_=function(marker){var distance=40000;var clusterToAddTo=null;var pos=marker.getPosition();for(var i=0,cluster;cluster=this.clusters_[i];i++){var center=cluster.getCenter();if(center){var d=this.distanceBetweenPoints_(center,marker.getPosition());if(d<distance){distance=d;clusterToAddTo=cluster;}}}
if(clusterToAddTo&&clusterToAddTo.isMarkerInClusterBounds(marker)){clusterToAddTo.addMarker(marker);}else{var cluster=new Cluster(this);cluster.addMarker(marker);this.clusters_.push(cluster);}};MarkerClusterer.prototype.createClusters_=function(){if(!this.ready_){return;}
var mapBounds=new google.maps.LatLngBounds(this.map_.getBounds().getSouthWest(),this.map_.getBounds().getNorthEast());var bounds=this.getExtendedBounds(mapBounds);for(var i=0,marker;marker=this.markers_[i];i++){if(!marker.isAdded&&this.isMarkerInBounds_(marker,bounds)){this.addToClosestCluster_(marker);}}};function Cluster(markerClusterer){this.markerClusterer_=markerClusterer;this.map_=markerClusterer.getMap();this.gridSize_=markerClusterer.getGridSize();this.minClusterSize_=markerClusterer.getMinClusterSize();this.averageCenter_=markerClusterer.isAverageCenter();this.center_=null;this.markers_=[];this.bounds_=null;this.clusterIcon_=new ClusterIcon(this,markerClusterer.getStyles(),markerClusterer.getGridSize());}
Cluster.prototype.isMarkerAlreadyAdded=function(marker){if(this.markers_.indexOf){return this.markers_.indexOf(marker)!=-1;}else{for(var i=0,m;m=this.markers_[i];i++){if(m==marker){return true;}}}
return false;};Cluster.prototype.addMarker=function(marker){if(this.isMarkerAlreadyAdded(marker)){return false;}
if(!this.center_){this.center_=marker.getPosition();this.calculateBounds_();}else{if(this.averageCenter_){var l=this.markers_.length+1;var lat=(this.center_.lat()*(l-1)+marker.getPosition().lat())/l;var lng=(this.center_.lng()*(l-1)+marker.getPosition().lng())/l;this.center_=new google.maps.LatLng(lat,lng);this.calculateBounds_();}}
marker.isAdded=true;this.markers_.push(marker);var len=this.markers_.length;if(len<this.minClusterSize_&&marker.getMap()!=this.map_){marker.setMap(this.map_);}
if(len==this.minClusterSize_){for(var i=0;i<len;i++){this.markers_[i].setMap(null);}}
if(len>=this.minClusterSize_){marker.setMap(null);}
this.updateIcon();return true;};Cluster.prototype.getMarkerClusterer=function(){return this.markerClusterer_;};Cluster.prototype.getBounds=function(){var bounds=new google.maps.LatLngBounds(this.center_,this.center_);var markers=this.getMarkers();for(var i=0,marker;marker=markers[i];i++){bounds.extend(marker.getPosition());}
return bounds;};Cluster.prototype.remove=function(){this.clusterIcon_.remove();this.markers_.length=0;delete this.markers_;};Cluster.prototype.getSize=function(){return this.markers_.length;};Cluster.prototype.getMarkers=function(){return this.markers_;};Cluster.prototype.getCenter=function(){return this.center_;};Cluster.prototype.calculateBounds_=function(){var bounds=new google.maps.LatLngBounds(this.center_,this.center_);this.bounds_=this.markerClusterer_.getExtendedBounds(bounds);};Cluster.prototype.isMarkerInClusterBounds=function(marker){return this.bounds_.contains(marker.getPosition());};Cluster.prototype.getMap=function(){return this.map_;};Cluster.prototype.updateIcon=function(){var zoom=this.map_.getZoom();var mz=this.markerClusterer_.getMaxZoom();if(mz&&zoom>mz){for(var i=0,marker;marker=this.markers_[i];i++){marker.setMap(this.map_);}
return;}
if(this.markers_.length<this.minClusterSize_){this.clusterIcon_.hide();return;}
var numStyles=this.markerClusterer_.getStyles().length;var sums=this.markerClusterer_.getCalculator()(this.markers_,numStyles);this.clusterIcon_.setCenter(this.center_);this.clusterIcon_.setSums(sums);this.clusterIcon_.show();};function ClusterIcon(cluster,styles,opt_padding){cluster.getMarkerClusterer().extend(ClusterIcon,google.maps.OverlayView);this.styles_=styles;this.padding_=opt_padding||0;this.cluster_=cluster;this.center_=null;this.map_=cluster.getMap();this.div_=null;this.sums_=null;this.visible_=false;this.setMap(this.map_);}
ClusterIcon.prototype.triggerClusterClick=function(){var markerClusterer=this.cluster_.getMarkerClusterer();google.maps.event.trigger(markerClusterer,'clusterclick',this.cluster_);if(markerClusterer.isZoomOnClick()){this.map_.fitBounds(this.cluster_.getBounds());}};ClusterIcon.prototype.onAdd=function(){this.div_=document.createElement('DIV');if(this.visible_){var pos=this.getPosFromLatLng_(this.center_);this.div_.style.cssText=this.createCss(pos);this.div_.innerHTML=this.sums_.text;}
var panes=this.getPanes();panes.overlayMouseTarget.appendChild(this.div_);var that=this;google.maps.event.addDomListener(this.div_,'click',function(){that.triggerClusterClick();});};ClusterIcon.prototype.getPosFromLatLng_=function(latlng){var pos=this.getProjection().fromLatLngToDivPixel(latlng);pos.x-=parseInt(this.width_/2,10);pos.y-=parseInt(this.height_/2,10);return pos;};ClusterIcon.prototype.draw=function(){if(this.visible_){var pos=this.getPosFromLatLng_(this.center_);this.div_.style.top=pos.y+'px';this.div_.style.left=pos.x+'px';}};ClusterIcon.prototype.hide=function(){if(this.div_){this.div_.style.display='none';}
this.visible_=false;};ClusterIcon.prototype.show=function(){if(this.div_){var pos=this.getPosFromLatLng_(this.center_);this.div_.style.cssText=this.createCss(pos);this.div_.style.display='';}
this.visible_=true;};ClusterIcon.prototype.remove=function(){this.setMap(null);};ClusterIcon.prototype.onRemove=function(){if(this.div_&&this.div_.parentNode){this.hide();this.div_.parentNode.removeChild(this.div_);this.div_=null;}};ClusterIcon.prototype.setSums=function(sums){this.sums_=sums;this.text_=sums.text;this.index_=sums.index;if(this.div_){this.div_.innerHTML=sums.text;}
this.useStyle();};ClusterIcon.prototype.useStyle=function(){var index=Math.max(0,this.sums_.index-1);index=Math.min(this.styles_.length-1,index);var style=this.styles_[index];this.url_=style['url'];this.height_=style['height'];this.width_=style['width'];this.textColor_=style['textColor'];this.anchor_=style['anchor'];this.textSize_=style['textSize'];this.backgroundPosition_=style['backgroundPosition'];};ClusterIcon.prototype.setCenter=function(center){this.center_=center;};ClusterIcon.prototype.createCss=function(pos){var style=[];style.push('background-image:url('+this.url_+');');var backgroundPosition=this.backgroundPosition_?this.backgroundPosition_:'0 0';style.push('background-position:'+backgroundPosition+';');if(typeof this.anchor_==='object'){if(typeof this.anchor_[0]==='number'&&this.anchor_[0]>0&&this.anchor_[0]<this.height_){style.push('height:'+(this.height_-this.anchor_[0])+'px; padding-top:'+this.anchor_[0]+'px;');}else{style.push('height:'+this.height_+'px; line-height:'+this.height_+'px;');}
if(typeof this.anchor_[1]==='number'&&this.anchor_[1]>0&&this.anchor_[1]<this.width_){style.push('width:'+(this.width_-this.anchor_[1])+'px; padding-left:'+this.anchor_[1]+'px;');}else{style.push('width:'+this.width_+'px; text-align:center;');}}else{style.push('height:'+this.height_+'px; line-height:'+
this.height_+'px; width:'+this.width_+'px; text-align:center;');}
var txtColor=this.textColor_?this.textColor_:'black';var txtSize=this.textSize_?this.textSize_:11;style.push('cursor:pointer; top:'+pos.y+'px; left:'+
pos.x+'px; color:'+txtColor+'; position:absolute; font-size:'+
txtSize+'px; font-family:Arial,sans-serif; font-weight:bold');return style.join('');};$('.map_button_search > .pickup_search_here').live('click',function(){pickup_sites.search_lat=pickup_sites.mapa.center.lat();pickup_sites.search_lng=pickup_sites.mapa.center.lng();pickup_sites.ajaxGetPickup(true);});