
var xpress_txt=[];xpress_txt["zipcode_invalid"]="Podany kod pocztowy jest nieprawidłowy.";xpress_txt["localization"]="Lokalizacja";xpress_txt["courier_not_available"]="Przykro nam, ale nasz ekspresowy kurier nie obsługuje tej okolicy. ";xpress_txt["courier_not_available2"]="Twoje zamówienie zostanie dostarczone w standardowym czasie, a kuriera wybierzesz podczas składania zamówienia.";xpress_txt["courier_not_available3"]="OK";xpress_txt["ajax_error"]="Wystąpił nieoczekiwany błąd. Proszę spróbować ponownie. ";xpress_txt["geolocation_error"]="Wystąpił błąd poczas sprawdzania kodu pocztowego. Proszę spróbować ponownie.";xpress_txt["geolocation_error2"]="Nie można pobrać kodu pocztowego. ";$.fn.textWidth=function(text,font){if(!$.fn.textWidth.fakeEl)$.fn.textWidth.fakeEl=$('<span>').hide().appendTo(document.body);$.fn.textWidth.fakeEl.text(text||this.val()||this.text()).css('font',font||this.css('font'));return $.fn.textWidth.fakeEl.width();};app_shop.fn.getParamsFormURL=function(_url){if(_url===undefined){_url=window.location.search;}
var afterMark=_url.split('?')[1];if(!afterMark){return{};}
_url=afterMark.split('&');var b={};for(var i=0;i<_url.length;++i)
{var p=_url[i].split('=',2);if(p.length==1)
b[p[0]]="";else
b[p[0]]=decodeURIComponent(p[1].replace(/\+/g," "));}
return b;};var filtering_callback=function(){}
var filtering_callback_click=function(){}
var xhr='';var v66412_ajax_off=""
var v66412_suwaczek_on=""
var filter_active_ajax=function(global,global_status,filter_id){if(!global){if($('#'+filter_id+'_toggle').is(':visible')){orderdetails_payments.ajaxLoadSite(1)}else{orderdetails_payments.ajaxLoadSite(0)}}
else{if(global_status==true){orderdetails_payments.ajaxLoadSite(1)}else{orderdetails_payments.ajaxLoadSite(0)}}}
var filter_response_ajax=function(xml){$('navigation>filtering>filter',xml).each(function(){var $this=$(this);var filter_id=$this.attr('id').replace('[','').replace(']','');if($('#'+filter_id).length&&filter_id!='filter_text'){$this.find('>item').each(function(){var $this=$(this);var quantity=$this.attr('quantity');var value=$this.attr('value');if(quantity){if(quantity>0){$('#'+filter_id+'_val'+value+'_quantity').show();$('#'+filter_id+'_val'+value+'_quantity span.filter_quantity_value').html(quantity);$('#'+filter_id+'_val'+value).removeAttr('disabled');$('#'+filter_id+'_'+value+'_box').removeClass('disabled');}else{$('#'+filter_id+'_val'+value+'_quantity').show();$('#'+filter_id+'_val'+value+'_quantity span.filter_quantity_value').html(quantity);$('#'+filter_id+'_val'+value).attr('disabled','disabled');$('#'+filter_id+'_'+value+'_box').addClass('disabled');}}else{$('#'+filter_id+'_val'+value+'_quantity').hide();$('#'+filter_id+'_val'+value).removeAttr('disabled');$('#'+filter_id+'_'+value+'_box').removeClass('disabled');}});$('div.filter_item.list_type').each(function(){if($(this).find('li').not('.disabled').length){$(this).find('.filter_header a').removeClass('active');}else{$(this).find('.filter_header a').addClass('active');}});filter_active_ajax(true,false);}else{}})}
var filter_prepare_ajaxfilter=function(){filter_fill_form();if(v66412_ajax_off==='true'){filter_submit();return false;}
var filter_data=$('#filter_form').serialize();xhr=filter_send_ajaxfilter(xhr,filter_data);filter_active_ajax(true,true);}
var filter_send_ajaxfilter=function(xhr,filter_data){xhr=xhr;if(xhr&&xhr.readystate!=4){xhr.abort();filter_active_ajax(true,false);}
xhr=$.ajax({type:'GET',url:'/search.php?'+filter_data+'&getProductXML=true&xmlType=filtering',dataType:'text',success:function(xml){filter_response_ajax(xml);},error:function(xml,sTextStatus,oErrorThrown){filter_active_ajax(true,false);}});return xhr;}
var txt_66412_008_001="wybierz datę"
$.fn.setOneHeight=function(){var a=0;$(this).each(function(){if($(this).height()>a){a=$(this).height();}});$(this).css('height',a);}
var align_filter_gfx=function(id){if(id){$('#'+id+' li').setOneHeight();}
else{$('#menu_filter div.filter_gfxonly').each(function(){if($(this).is(':visible')){$(this).find('li').setOneHeight();}});}}
function set_filter_cookie(){var filter_hidden_list=new Array();$('#menu_filter a.filter_toggle.active').each(function(){filter_hidden_list.push($(this).attr('href').substring(8));});$.cookie('filter_hidden','',{expires:355});$.cookie('filter_hidden',filter_hidden_list,{expires:355});}
function get_filter_cookie(){var flistA=$.cookie('filter_hidden');if(!!flistA){var flist=flistA.split(',');for(var i=0;i<flist.length;i++){}}}
var filter_showall=function(obj){if(obj.hasClass('active')){obj.removeClass('active');obj.html(filter_pokaz);$('#'+obj.attr('data-filter')+' li.filterhidden').removeClass('showhidden');}else{obj.addClass('active');obj.html(filter_ukryj);$('#'+obj.attr('data-filter')+' li.filterhidden').addClass('showhidden');}}
var filter_fill_form_action=function(){var params=app_shop.fn.getParamsFormURL($('#filter_form').attr('action'));for(var k in params){var oInput=$('<input type="hidden">');oInput.attr('name',k);oInput.attr('value',params[k]);$('#filter_form').append(oInput);}}
var filter_fill_form=function(){$('#menu_filter div.filter_item.list_type').each(function(){var fID=$(this).attr('id');var fvt=new Array();$('#'+fID+'_content input[type=checkbox]:checked').each(function(){if($(this).attr('disabled')!='disabled'){fvt.push($(this).val());}});$('#'+fID+'_form').val(fvt);});if($.cookie('f_getPriceRange')=='1'){$('#menu_filter div.filter_range').each(function(){var fV=$('#'+$(this).attr('data-filter')+'_range_from').val()+'-'+$('#'+$(this).attr('data-filter')+'_range_to').val();if(fV!='-'){$('#'+$(this).attr('data-filter')+'_form').val(fV);}});}
$('#menu_filter div.filter_item.dual_type input').each(function(){if($(this).is(':checked')&&$(this).attr('disabled')!='disabled'){$('#'+$(this).attr('id')+'_form').val('y');}
else{$('#'+$(this).attr('id')+'_form').val('')}});if($('#filter_text_input').length&&$('#filter_text_input').val()!=$('#filter_text_input').attr('data-filter')){$('#filter_text_form').val($('#filter_text_input').val());}
filtering_callback_click();}
var filter_submit=function(){filter_fill_form();filter_fill_form_action();$('#filter_form').submit();}
var mark_active=function(obj){if($('#filter_dual #'+obj).length){obj_box=obj+'_y_box';if($('#'+obj).is(':checked')){$('#'+obj_box).addClass('enabled');}else{$('#'+obj_box).removeClass('enabled');}}else{obj_box=obj.replace('_val','_')+'_box';if($('#'+obj).is(':checked')){$('#'+obj_box).addClass('enabled');}else{$('#'+obj_box).removeClass('enabled');}}}
app_shop.fn.xpressCouriersInit=function(){$('.filter_content.xpress input').on('change',function(){var $this=$(this);app_shop.vars.clickedXPRESS=$this.attr('id');app_shop.vars.clickedXPRESS=app_shop.vars.clickedXPRESS.split('_');app_shop.vars.clickedXPRESS=app_shop.vars.clickedXPRESS[1];if($this.is(':checked')&&$this.parent().attr('data-localized')=='false'){$('body').dialog({width:300,content:$('#xpress_toplayer').html(),wrapperClass:'xpress_zipcode_verification',fixed:false});}});$('input#xpress_zipcode').live('input',function(){clearTimeout(app_shop.formControl.timeHandle);obj=$(this);app_shop.formControl.timeHandle=setTimeout(function(){app_shop.formControl.validate(obj);},500);});$('#xpress_zipcode_submit').live('click',function(){var $input=$(this).parent().siblings('.form-group').find('#xpress_zipcode');var region=$input.data('region');var zipcode=$input.val();if(!$input.val()){$('input#xpress_zipcode').addClass('error');return false;}
var _data="client_zipcode="+zipcode+'&'+region;$.ajax({url:'/ajax/client-new.php?validAjax=true',type:'post',data:_data,dataType:'json',beforeSend:function(){orderdetails_payments.ajaxLoadSite(1)},success:function(json){var err=json.errno;if(err>0){Alertek.show_alert(xpress_txt["zipcode_invalid"]);$('input#xpress_zipcode').addClass('error');orderdetails_payments.ajaxLoadSite(0)
return false;}
$.ajax({url:'/ajax/client-new.php?setClientSamedayLocation=1&zipcode='+zipcode,type:'post',dataType:'json',success:function(){var filterUrl=$(location).attr('href');var filter_vals=$('form#filter_form').serialize();$.ajax({url:'/search.php?'+filter_vals+'&getProductXML=true&xmlType=filtering',dataType:'xml',success:function(xml){if($(xml).find(app_shop.vars.clickedXPRESS).attr('client_localized')=='true'&&$(xml).find(app_shop.vars.clickedXPRESS).attr('service_available_for_current_location')=='true')
$('#filter_form').submit();else
$('body').dialog({width:300,content:$('#xpress_toplayer_error').html(),wrapperClass:'xpress_zipcode_verification',fixed:false});orderdetails_payments.ajaxLoadSite(0)}})},error:function(){orderdetails_payments.ajaxLoadSite(0)
Alertek.show_alert();}})},error:function(){orderdetails_payments.ajaxLoadSite(0)
Alertek.show_alert(xpress_txt["geolocation_error"]);}})
return false;});$('#xpress_zipcode_geolocation').live('click',function(){if(navigator.geolocation){navigator.geolocation.getCurrentPosition(function(position){orderdetails_payments.ajaxLoadSite(1)
var lat=position.coords.latitude;var long=position.coords.longitude;var point=new google.maps.LatLng(lat,long);new google.maps.Geocoder().geocode({'latLng':point},function(res,status){var zipcode=res[0].formatted_address.match(/\d{2}-\d{3}/);if(zipcode)
$('input#xpress_zipcode').val(zipcode[0]);else
Alertek.show_alert(xpress_txt["geolocation_error2"]);orderdetails_payments.ajaxLoadSite(0)});});}
return false;});$('#express_close_dialog').live('click',function(){$('#dialog_close').click();return false;});}
function menu_filter_init(){$('#menu_filter div.menu_filter_wrapper input[type=checkbox]').each(function(){mark_active($(this).attr('id'));});$('#menu_filter div.menu_filter_wrapper input[type=checkbox]').change(function(){mark_active($(this).attr('id'));});filter_fill_form();$('#menu_filter input[type=text]').on('keyup',function(e){if(e.which==13){filter_submit();}});$('#menu_filter div.filter_item.list_type input[type="checkbox"]').click(function(){var fID=String($(this).attr('id')).substring(0,String($(this).attr('id')).indexOf('_val'));$('a.filter_submit[data-filter="'+fID+'"]').show('fast');var fvt=new Array();$('#'+fID+'_content input[type="checkbox"]').each(function(){if($(this).is(':checked')){fvt.push($(this).val());}});$('#'+fID+'_form').val(fvt);if($(this).attr('id')!='filter_price_range_from'&&$(this).attr('id')!='filter_price_range_to'&&$(this).attr('id')!='filter_text_input'&&$(this).attr('id')!='filter_date_datepicker'&&$(this).attr('data-filter')!='filter_date_option'){filter_prepare_ajaxfilter();}});$('#menu_filter div.filter_item.dual_type input').click(function(){if($(this).is(':checked')){$('#'+$(this).attr('id')+'_form').val('y');}
else{$('#'+$(this).attr('id')+'_form').val('')}
$('a.filter_submit[data-filter="filter_dual"]').show('fast');filter_prepare_ajaxfilter();});$('#filter_text_input').focus(function(){if($(this).val()==$(this).attr('data-filter')){$(this).val('');}});$('#filter_text_submit').click(function(){filter_submit();});$('#filter_text_input').keyup(function(){$('#filter_text_form').val($('#filter_text_input').val());});$('#menu_filter a.filter_submit_range').click(function(){filter_fill_form();$('#menu_filter div.filter_range').each(function(){var fV=$('#'+$(this).attr('data-filter')+'_range_from').val()+'-'+$('#'+$(this).attr('data-filter')+'_range_to').val();if(fV!='-'){$('#'+$(this).attr('data-filter')+'_form').val(fV);}});$('#filter_form').submit();});if($('#filter_date').length){$('#filter_date input[type="checkbox"]').click(function(){var tP=$(this).prop('checked');$('#filter_date input').prop('checked',false);if(!tP){$(this).prop('checked',false);}else{$(this).prop('checked',true);}
if($(this).attr('id')!='filter_date_calendar_picker'){$('#filter_date_calendar_picker').val('');$(this).parents('ul').find('span.filter_calendar_from').hide();$('#filter_date_datepicker').val(txt_66412_008_001);}
filter_prepare_ajaxfilter();});$('.filter_datepicker').datepicker({onSelect:function(dateText,inst){$(this).parent().find('span.filter_calendar_from').show();$('#'+$(this).attr('id').replace('_datepicker','')+' input[type="checkbox"]').prop('checked',false);$(this).parent().find('input.filter_calendar').val($(this).val());$(this).parent().find('input.filter_calendar').prop('checked',true);$('#'+$(this).attr('id').replace('_datepicker','_submit')).show('fast');},dateFormat:iaical_dateFormat,dayNamesMin:iaical_daysShort,monthNames:iaical_monthNames,nextText:iaical_monthNext,firstDay:iaical_firstDay,prevText:iaical_monthPrev});$('.filter_datepicker').datepicker("option","dateFormat","yy-mm-dd");datepicker_min_year=parseInt(datepicker_min.substring(0,4));datepicker_min_month=parseInt(datepicker_min.substring(5,7));datepicker_min_day=parseInt(datepicker_min.substring(8,10));datepicker_max_year=parseInt(datepicker_max.substring(0,4));datepicker_max_month=parseInt(datepicker_max.substring(5,7));datepicker_max_day=parseInt(datepicker_max.substring(8,10));var minDate=$(".filter_datepicker").datepicker("option","minDate");$(".filter_datepicker").datepicker("option","minDate",new Date(datepicker_min_year,datepicker_min_month-1,datepicker_min_day));var maxDate=$(".filter_datepicker").datepicker("option","maxDate");$(".filter_datepicker").datepicker("option","maxDate",new Date(datepicker_max_year,datepicker_max_month-1,datepicker_max_day));$('.filter_datepicker').each(function(){$(this).val($(this).attr('data-filter'));});}
if($('#menu_filter').length){$('#ui-datepicker-div a').live('click',function(){filter_prepare_ajaxfilter();});}
get_filter_cookie();$('a.filter_submit').click(function(){filter_submit();});$('a.show_all').click(function(){filter_showall($(this));});$('#menu_filter .filter_header').click(function(){$('.content_active').removeClass('content_active');$(this).next().addClass('content_active');$('.filter_content:not(.content_active)').removeClass('filter_content_open');$('.content_active').toggleClass('filter_content_open');set_filter_cookie();});$('#menu_filter div.filter_item.list_type label').click(function(){if(!$('#'+$(this).attr('for').replace('_val','_')+'_box').hasClass('disabled')){if($('#'+$(this).attr('for')).prop('checked')){$(this).removeClass('active');}
else{$(this).addClass('active');}}});simple_tooltip("div.filter_gfxonly img","filter_tooltip");$('#filter_buttons a.filters_submit').click(function(){filter_submit();});if(v66412_suwaczek_on){if($.ui.slider){$("#slider-price").slider({range:true,min:parseInt($("#min_price_start").val()),max:parseInt($("#max_price_start").val()),values:[parseInt($("#min_price_set").val()||$("#min_price_start").val()),parseInt($("#max_price_set").val()||$("#max_price_start").val())],slide:function(event,ui){$("#filter_price_range_from").val(ui.values[0]);$("#filter_price_range_to").val(ui.values[1]);},stop:function(event,ui){$("#filter_price_range_from").val(ui.values[0]);$("#filter_price_range_to").val(ui.values[1]);}});}}
$('#filter_price_range_content input').live('focus click change',function(){$.cookie('f_getPriceRange','1');});$('#filter_price_content input, #filter_price_content label').live('click',function(){$.cookie('f_getPriceRange','0');});app_shop.fn.xpressCouriersInit();}
$(window).load(function(){align_filter_gfx();if(!$('#filter_price_list').length)$.cookie('f_getPriceRange','0');});$('.filter_search input').die().live('keyup',function(){var input=$(this);var filter=input.val().toUpperCase();var ul=$(this).parents('.filter_content_sub').find('ul');var li=ul.find('li');$(this).parents('.filter_content_sub').find('.show_all:not(.active)').click().hide();if(filter==""){$(this).parents('.filter_content_sub').find('.show_all.active').click().show();}
li.each(function(){if($(this).find('label').text().toUpperCase().indexOf(filter)>-1){$(this).show();}else{$(this).hide();}});});app_shop.run(function(){$('.filter_sub_header').live('click',function(){if(app_shop.vars.view>2){$('.filter_sub_header').removeClass('active');$(this).addClass('active');var groupId=$(this).attr('group-id');$('.filter_content_sub').removeClass('active');$('.filter_content_sub[group-id="'+groupId+'"]').addClass('active');$('body').resize();}else{$(this).toggleClass('active');var groupId=$(this).attr('group-id');$('.filter_content_sub[group-id="'+groupId+'"]').toggleClass('active');}});$('.group_header_wrapper').each(function(){$(this).find($('.filter_sub_header ').first()).click();});},'all','.filter_sub_header');app_shop.run(function(){$('.group_content_wrapper li').die().live('click',function(event){var obj=$(this).parents('.filter_content_sub_items');if(obj.find($('.filter_checkbox:checked')).length>0){obj.find('.filter_close').hide();obj.find('.filter_submit').show();}else{obj.find('.filter_close').show();obj.find('.filter_submit').hide();}});},'all','.group_content_wrapper .filter_name_wrapper label');app_shop.run(function(){$('.filter_close').live('click',function(){$(this).closest('.group_wrapper').hide()
$('body').resize()});},'all','.filter_close');app_shop.run(function(){$('aside').append($('#menu_filter'));$('#paging_setting_top').prepend($('#menu_filter_sub > .search_setting'));$('#menu_filter_sub').prepend($('#paging_setting_top > .search_setting:first-child'));$('#search').before($('#filter_list'));$('.filter_sub_header').each(function(){var id=$(this).attr('group-id');var ul=$('.filter_content_sub[group-id="'+id+'"]');$(this).after(ul);});},[1,2],'#menu_filter');app_shop.run(function(){$('.search_categoriesdescription').after($('#menu_filter'));$('#paging_setting_top').prepend($('#menu_filter_sub > .search_setting'));$('#search').before($('#filter_list'))
$('.group_wrapper').each(function(){$(this).find($('.group_content_wrapper')).append($(this).find($('.filter_content_sub')));});$('.filter_content_sub').removeClass('active');$('.group_header_wrapper').each(function(){$(this).find($('.filter_sub_header ').first()).click();});},[3,4],'#menu_filter');app_shop.run(function(){$('.menu_filter_wrapper').prepend($('#filter_sizes'));},'all','#filter_sizes');app_shop.run(function(){$('#menu_filter .group_wrapper li').live('click',function(){var ul=$(this).closest('ul');var selectedCount=ul.find($('input[type="checkbox"]:checked')).length;if(selectedCount>0){$('.filter_sub_header.active .filter_count').text(selectedCount);$('.filter_sub_header.active').addClass('count');$('.filter_sub_header.active .filter_count_wrapper').css('display','block');}else{$('.filter_sub_header.active').removeClass('count');$('.filter_sub_header.active .filter_count_wrapper').css('display','none');}});},'all','.filter_content_sub');